### ISSUE TITLE
three_way_fork needs one more input parameter to show fork number in each round

### ISSUE THREAD

**Issue by hadipourh** [fukai6/milp_speck#4]
Regarding to speck_line_find: I think three_way_fork function must have one more parameter to represent the fork number in each round, because in each round two forks are used. At the present, for the same bit positions in the same round but in different fork, we have the same dummy variables, which would not be correct.

**Comment by fukai6** [comment]
![default](https://user-images.githubusercontent.com/17399753/49705183-b98a4100-fc57-11e8-9a33-bde2f07237f9.png)
emmm i think there is the parameter you say

**Comment by hadipourh** [comment]
But you have not updated the repository yet so that we can access to
"ConstraintGenerator.xor...". Could you please update it. Thank you for
your attention.

**Comment by hadipourh** [comment]
Why do you assign (blocksize + 1) to ``h`` within the ``genVars_Objective`` function? I think ``int(blocksize /2) + 1`` is enough.

**Comment by wang-sw** [comment]
This is the error I'm getting:

File "/milp_speck/speck_diff_find.py", line 60, in genConstraints_of_Round
constraints = constraints + ConstraintGenerator.xorConstraints(x3, y1, y0)
NameError: name 'ConstraintGenerator' is not defined

**Comment by jinhaichen** [comment]
Can you provide the two files ConstraintGenerator.py and BasicTools.py? Thanks.

**Comment by fukai6** [comment]
> ConstraintGenerator.py

**Comment by fukai6** [comment]
> Can you provide the two files ConstraintGenerator.py and BasicTools.py? Thanks.

sorry，i do not have 2 py.
